version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev      
    volumes:
     - .:/code
    ports:
     - '3334:5000'
    environment:
      ENV_STAGE: dev
    restart: unless-stopped
    depends_on:
     - redis
  redis:
    image: redis:3.2
    container_name: sample_redis_dev
    restart: unless-stopped
