version: '2'
services:
  redis:
    image: redis:3.2
    container_name: sample_redis_stg
    restart: unless-stopped
    volumes:
      - /var/db/redis/stg:/data
    command: redis-server --appendonly yes
networks:
  default:
    external:
      name: sample_stg
